output_dir: 1_3B_32_16_UniPC_GAN_adaptive_weight_0.5dist
logging_dir: logs
seed: 42

report_to:
  wandb: true
  project_name: Spark-Wan
  wandb_name: 1_3B_32_16_UniPC_GAN_adaptive_weight_0.5dist
  wandb_notes: ""

parallel_config:
  sp_size: 1
  reshard_after_forward: false

data_config:
  instance_data_root: "scripts/sucai.json"
  height: 480
  width: 832
  fps: 8
  max_num_frames: 81
  dataloader_num_workers: 0

model_config:
  pretrained_lora_path: null
  pretrained_model_name_or_path: "/storage/ysh/Ckpts/Wan2.1-T2V-1.3B-Diffusers/"
  compile_transformer: false
  fsdp_transformer: true
  fsdp_discriminator: true
  fsdp_text_encoder: false
  lora_rank: 128
  lora_alpha: 256.0
  lora_dropout: 0.0
  flow_shift: 8.0
  is_train_lora: true
  lora_target_modules: null # set to null but not null inner.

validation_config:
  validation_steps: 100
  validation_prompt: "A stylish woman walks down a Tokyo street filled with warm glowing neon and animated city signage. She wears a black leather jacket, a long red dress, and black boots, and carries a black purse. She wears sunglasses and red lipstick. She walks confidently and casually. The street is damp and reflective, creating a mirror effect of the colorful lights. Many pedestrians walk about."
  validation_prompt_separator: ":::"
  num_validation_videos: 1
  log_teacher_sample: false

training_config:
  resume_from_checkpoint: null
  gradient_accumulation_steps: 1
  max_train_steps: null
  checkpointing_steps: 200
  train_batch_size: 1
  num_train_epochs: 10
  gradient_checkpointing: true
  disc_gradient_checkpointing: true
  mixed_precision: fp16
  learning_rate: 0.00001
  lr_scheduler: constant
  optimizer: adamw
  adam_beta1: 0.9
  adam_beta2: 0.99
  adam_weight_decay: 0.0001
  adam_epsilon: 1e-08
  max_grad_norm: 1.0

step_distill_config:
  teacher_step: 32
  student_step: 16
  guidance_scale_max: 8.0
  guidance_scale_min: 4.0
  is_gan_distill: true
  disc_interval: 2
  disc_start: 0
  distance_weight: 1.0
  disc_weight: 0.5
  scheduler_type: UniPC
  adaptive_weight: true
  reduce_func: sum